// XPR built-in registry. Hand-curated from xpr-js/src/functions.ts (ground truth).
// Every entry MUST trace back to a real GLOBAL_FUNCTIONS, GLOBAL_CONSTANTS, or
// callXxxMethod case in that file. Powers W2.1 autocompletion and will be
// reused by W2.2 hover docs.

export type BuiltinKind = 'function' | 'method' | 'constant'
export type BuiltinReceiver = 'array' | 'string' | 'object' | 'regex' | 'date'
export type BuiltinVersion = 'v0.1' | 'v0.2' | 'v0.3' | 'v0.4' | 'v0.5'

export interface Builtin {
  name: string
  kind: BuiltinKind
  signature: string
  description: string
  receiver?: BuiltinReceiver
  version: BuiltinVersion
}

export const BUILTINS: Builtin[] = [
  { name: 'round', kind: 'function', signature: 'round(n: number): number', description: 'Round to nearest integer', version: 'v0.1' },
  { name: 'floor', kind: 'function', signature: 'floor(n: number): number', description: 'Round down to nearest integer', version: 'v0.1' },
  { name: 'ceil', kind: 'function', signature: 'ceil(n: number): number', description: 'Round up to nearest integer', version: 'v0.1' },
  { name: 'abs', kind: 'function', signature: 'abs(n: number): number', description: 'Absolute value', version: 'v0.1' },
  { name: 'min', kind: 'function', signature: 'min(a: number, b: number, ...): number', description: 'Smallest of two or more numbers', version: 'v0.1' },
  { name: 'max', kind: 'function', signature: 'max(a: number, b: number, ...): number', description: 'Largest of two or more numbers', version: 'v0.1' },
  { name: 'type', kind: 'function', signature: 'type(v: any): string', description: 'Type name (number, string, array, object, regex, null, boolean, function)', version: 'v0.1' },
  { name: 'int', kind: 'function', signature: 'int(v: number | string): number', description: 'Convert to integer by truncation; throws on non-numeric strings', version: 'v0.1' },
  { name: 'float', kind: 'function', signature: 'float(v: number | string): number', description: 'Convert to floating-point number', version: 'v0.1' },
  { name: 'string', kind: 'function', signature: 'string(v: any): string', description: 'Convert any value to its string representation', version: 'v0.1' },
  { name: 'bool', kind: 'function', signature: 'bool(v: any): boolean', description: 'Coerce to boolean (false, null, 0, "" are false)', version: 'v0.1' },
  { name: 'range', kind: 'function', signature: 'range(start?: number, end: number, step?: number): number[]', description: 'Inclusive-start, exclusive-end integer range', version: 'v0.1' },
  { name: 'now', kind: 'function', signature: 'now(): number', description: 'Current time as epoch milliseconds', version: 'v0.3' },
  { name: 'parseDate', kind: 'function', signature: 'parseDate(s: string, fmt?: string): number', description: 'Parse date string to epoch ms (ISO 8601 default; ICU tokens yyyy MM dd HH mm ss SSS)', version: 'v0.3' },
  { name: 'formatDate', kind: 'function', signature: 'formatDate(date: number, fmt: string): string', description: 'Format epoch ms using ICU tokens (yyyy MM dd HH mm ss SSS)', version: 'v0.3' },
  { name: 'year', kind: 'function', signature: 'year(date: number): number', description: 'UTC year from epoch ms', version: 'v0.3' },
  { name: 'month', kind: 'function', signature: 'month(date: number): number', description: 'UTC month (1-12) from epoch ms', version: 'v0.3' },
  { name: 'day', kind: 'function', signature: 'day(date: number): number', description: 'UTC day of month (1-31) from epoch ms', version: 'v0.3' },
  { name: 'hour', kind: 'function', signature: 'hour(date: number): number', description: 'UTC hour (0-23) from epoch ms', version: 'v0.3' },
  { name: 'minute', kind: 'function', signature: 'minute(date: number): number', description: 'UTC minute (0-59) from epoch ms', version: 'v0.3' },
  { name: 'second', kind: 'function', signature: 'second(date: number): number', description: 'UTC second (0-59) from epoch ms', version: 'v0.3' },
  { name: 'millisecond', kind: 'function', signature: 'millisecond(date: number): number', description: 'UTC millisecond (0-999) from epoch ms', version: 'v0.3' },
  { name: 'dateAdd', kind: 'function', signature: 'dateAdd(date: number, amount: number, unit: string): number', description: 'Add amount of unit (years|months|days|hours|minutes|seconds|milliseconds)', version: 'v0.3' },
  { name: 'dateDiff', kind: 'function', signature: 'dateDiff(d1: number, d2: number, unit: string): number', description: 'd2 - d1 in unit (years|months|days|hours|minutes|seconds|milliseconds)', version: 'v0.3' },
  { name: 'matches', kind: 'function', signature: 'matches(s: string, pattern: string): boolean', description: 'Test whether string matches regex pattern (RE2 flavor; inline (?flags))', version: 'v0.3' },
  { name: 'match', kind: 'function', signature: 'match(s: string, pattern: string): string | null', description: 'First regex match in string (null if no match)', version: 'v0.3' },
  { name: 'matchAll', kind: 'function', signature: 'matchAll(s: string, pattern: string): string[]', description: 'All non-overlapping regex matches in string', version: 'v0.3' },
  { name: 'replacePattern', kind: 'function', signature: 'replacePattern(s: string, pattern: string, replacement: string): string', description: 'Replace every regex match with replacement string', version: 'v0.3' },
  { name: 'sqrt', kind: 'function', signature: 'sqrt(n: number): number', description: 'Square root (throws on negative input)', version: 'v0.5' },
  { name: 'log', kind: 'function', signature: 'log(n: number): number', description: 'Natural logarithm (throws on non-positive input)', version: 'v0.5' },
  { name: 'pow', kind: 'function', signature: 'pow(x: number, y: number): number', description: 'x raised to the power of y', version: 'v0.5' },
  { name: 'random', kind: 'function', signature: 'random(): number', description: 'Pseudo-random number in [0, 1)', version: 'v0.5' },
  { name: 'sign', kind: 'function', signature: 'sign(n: number): number', description: 'Sign of n: -1, 0, or 1', version: 'v0.5' },
  { name: 'trunc', kind: 'function', signature: 'trunc(n: number): number', description: 'Truncate toward zero (drop fractional part)', version: 'v0.5' },
  { name: 'isNumber', kind: 'function', signature: 'isNumber(v: any): boolean', description: 'True if v is a number', version: 'v0.5' },
  { name: 'isString', kind: 'function', signature: 'isString(v: any): boolean', description: 'True if v is a string', version: 'v0.5' },
  { name: 'isArray', kind: 'function', signature: 'isArray(v: any): boolean', description: 'True if v is an array', version: 'v0.5' },
  { name: 'isNull', kind: 'function', signature: 'isNull(v: any): boolean', description: 'True if v is null', version: 'v0.5' },
  { name: 'isObject', kind: 'function', signature: 'isObject(v: any): boolean', description: 'True if v is a plain object (not array, not regex)', version: 'v0.5' },
  { name: 'isRegex', kind: 'function', signature: 'isRegex(v: any): boolean', description: 'True if v is a regex value', version: 'v0.5' },
  { name: 'fromEntries', kind: 'function', signature: 'fromEntries(pairs: [string, any][]): object', description: 'Build an object from an array of [key, value] pairs (keys sorted)', version: 'v0.5' },
  { name: 'PI', kind: 'constant', signature: 'PI: number', description: 'Math.PI (3.14159…)', version: 'v0.5' },
  { name: 'E', kind: 'constant', signature: 'E: number', description: "Euler's number (2.71828…)", version: 'v0.5' },
  { name: 'map', kind: 'method', receiver: 'array', signature: 'array.map(fn: (el) => any): array', description: 'Transform each element with fn', version: 'v0.1' },
  { name: 'filter', kind: 'method', receiver: 'array', signature: 'array.filter(predicate: (el) => boolean): array', description: 'Keep elements where predicate is truthy', version: 'v0.1' },
  { name: 'reduce', kind: 'method', receiver: 'array', signature: 'array.reduce(fn: (acc, el) => any, init: any): any', description: 'Fold left into a single value', version: 'v0.1' },
  { name: 'find', kind: 'method', receiver: 'array', signature: 'array.find(predicate: (el) => boolean): any | null', description: 'First element matching predicate (null if none)', version: 'v0.1' },
  { name: 'some', kind: 'method', receiver: 'array', signature: 'array.some(predicate: (el) => boolean): boolean', description: 'True if predicate matches any element', version: 'v0.1' },
  { name: 'every', kind: 'method', receiver: 'array', signature: 'array.every(predicate: (el) => boolean): boolean', description: 'True if predicate matches every element', version: 'v0.1' },
  { name: 'flatMap', kind: 'method', receiver: 'array', signature: 'array.flatMap(fn: (el) => any | any[]): array', description: 'Map then flatten one level', version: 'v0.1' },
  { name: 'sort', kind: 'method', receiver: 'array', signature: 'array.sort(cmp?: (a, b) => number): array', description: 'Stable sort (natural order without cmp; returns new array)', version: 'v0.1' },
  { name: 'reverse', kind: 'method', receiver: 'array', signature: 'array.reverse(): array', description: 'Reversed copy of array', version: 'v0.1' },
  { name: 'includes', kind: 'method', receiver: 'array', signature: 'array.includes(value: any): boolean', description: 'True if array contains value (strict equality)', version: 'v0.1' },
  { name: 'indexOf', kind: 'method', receiver: 'array', signature: 'array.indexOf(value: any): number', description: 'First index of value, or -1 if absent', version: 'v0.1' },
  { name: 'slice', kind: 'method', receiver: 'array', signature: 'array.slice(start: number, end?: number): array', description: 'Sub-array from start (inclusive) to end (exclusive)', version: 'v0.1' },
  { name: 'join', kind: 'method', receiver: 'array', signature: 'array.join(sep: string): string', description: 'Concatenate elements with separator', version: 'v0.1' },
  { name: 'concat', kind: 'method', receiver: 'array', signature: 'array.concat(other: array): array', description: 'Concatenate two arrays', version: 'v0.2' },
  { name: 'flat', kind: 'method', receiver: 'array', signature: 'array.flat(): array', description: 'Flatten one level of nested arrays', version: 'v0.2' },
  { name: 'unique', kind: 'method', receiver: 'array', signature: 'array.unique(): array', description: 'Distinct elements preserving order of first occurrence', version: 'v0.2' },
  { name: 'zip', kind: 'method', receiver: 'array', signature: 'array.zip(other: array): array', description: 'Pairwise zip with another array (truncates to shorter length)', version: 'v0.2' },
  { name: 'chunk', kind: 'method', receiver: 'array', signature: 'array.chunk(size: number): array[]', description: 'Split into sub-arrays of given size', version: 'v0.2' },
  { name: 'groupBy', kind: 'method', receiver: 'array', signature: 'array.groupBy(keyFn: (el) => any): object', description: 'Group elements by key (keys sorted alphabetically)', version: 'v0.2' },
  { name: 'sortBy', kind: 'method', receiver: 'array', signature: 'array.sortBy(keyFn: (el) => number | string): array', description: 'Sort by computed key (all numbers or all strings)', version: 'v0.5' },
  { name: 'take', kind: 'method', receiver: 'array', signature: 'array.take(n: number): array', description: 'First n elements', version: 'v0.5' },
  { name: 'drop', kind: 'method', receiver: 'array', signature: 'array.drop(n: number): array', description: 'All but the first n elements', version: 'v0.5' },
  { name: 'count', kind: 'method', receiver: 'array', signature: 'array.count(predicate: (el) => boolean): number', description: 'Count elements where predicate is truthy', version: 'v0.5' },
  { name: 'sum', kind: 'method', receiver: 'array', signature: 'array.sum(): number', description: 'Sum of numeric elements (0 on empty)', version: 'v0.5' },
  { name: 'avg', kind: 'method', receiver: 'array', signature: 'array.avg(): number', description: 'Mean of numeric elements (throws on empty)', version: 'v0.5' },
  { name: 'compact', kind: 'method', receiver: 'array', signature: 'array.compact(): array', description: 'Drop null elements', version: 'v0.5' },
  { name: 'partition', kind: 'method', receiver: 'array', signature: 'array.partition(predicate: (el) => boolean): [array, array]', description: 'Split into [matches, non-matches] by predicate', version: 'v0.5' },
  { name: 'keyBy', kind: 'method', receiver: 'array', signature: 'array.keyBy(keyFn: (el) => any): object', description: 'Index elements by key (last write wins; keys sorted)', version: 'v0.5' },
  { name: 'min', kind: 'method', receiver: 'array', signature: 'array.min(): number', description: 'Smallest numeric element (throws on empty)', version: 'v0.5' },
  { name: 'max', kind: 'method', receiver: 'array', signature: 'array.max(): number', description: 'Largest numeric element (throws on empty)', version: 'v0.5' },
  { name: 'first', kind: 'method', receiver: 'array', signature: 'array.first(): any | null', description: 'First element (null if empty)', version: 'v0.5' },
  { name: 'last', kind: 'method', receiver: 'array', signature: 'array.last(): any | null', description: 'Last element (null if empty)', version: 'v0.5' },
  { name: 'len', kind: 'method', receiver: 'string', signature: 'string.len(): number', description: 'Length in code units', version: 'v0.1' },
  { name: 'upper', kind: 'method', receiver: 'string', signature: 'string.upper(): string', description: 'Upper-case copy', version: 'v0.1' },
  { name: 'lower', kind: 'method', receiver: 'string', signature: 'string.lower(): string', description: 'Lower-case copy', version: 'v0.1' },
  { name: 'trim', kind: 'method', receiver: 'string', signature: 'string.trim(): string', description: 'Drop leading and trailing whitespace', version: 'v0.1' },
  { name: 'startsWith', kind: 'method', receiver: 'string', signature: 'string.startsWith(prefix: string): boolean', description: 'True if string begins with prefix', version: 'v0.1' },
  { name: 'endsWith', kind: 'method', receiver: 'string', signature: 'string.endsWith(suffix: string): boolean', description: 'True if string ends with suffix', version: 'v0.1' },
  { name: 'contains', kind: 'method', receiver: 'string', signature: 'string.contains(needle: string): boolean', description: 'True if string contains needle', version: 'v0.1' },
  { name: 'split', kind: 'method', receiver: 'string', signature: 'string.split(sep: string | regex): string[]', description: 'Split by separator string or regex', version: 'v0.1' },
  { name: 'replace', kind: 'method', receiver: 'string', signature: 'string.replace(search: string | regex, replacement: string): string', description: 'Replace all occurrences (regex is implicitly global)', version: 'v0.1' },
  { name: 'match', kind: 'method', receiver: 'string', signature: 'string.match(re: regex): string | null', description: 'First regex match in string (null if none)', version: 'v0.4' },
  { name: 'slice', kind: 'method', receiver: 'string', signature: 'string.slice(start: number, end?: number): string', description: 'Substring from start (inclusive) to end (exclusive)', version: 'v0.1' },
  { name: 'indexOf', kind: 'method', receiver: 'string', signature: 'string.indexOf(needle: string): number', description: 'First index of needle, or -1', version: 'v0.1' },
  { name: 'repeat', kind: 'method', receiver: 'string', signature: 'string.repeat(n: number): string', description: 'String repeated n times', version: 'v0.2' },
  { name: 'trimStart', kind: 'method', receiver: 'string', signature: 'string.trimStart(): string', description: 'Drop leading whitespace', version: 'v0.2' },
  { name: 'trimEnd', kind: 'method', receiver: 'string', signature: 'string.trimEnd(): string', description: 'Drop trailing whitespace', version: 'v0.2' },
  { name: 'charAt', kind: 'method', receiver: 'string', signature: 'string.charAt(index: number): string', description: 'Character at index (empty string if out of range)', version: 'v0.2' },
  { name: 'padStart', kind: 'method', receiver: 'string', signature: 'string.padStart(width: number, fill?: string): string', description: 'Pad on the left to width with fill (default space)', version: 'v0.2' },
  { name: 'padEnd', kind: 'method', receiver: 'string', signature: 'string.padEnd(width: number, fill?: string): string', description: 'Pad on the right to width with fill (default space)', version: 'v0.2' },
  { name: 'keys', kind: 'method', receiver: 'object', signature: 'object.keys(): string[]', description: 'Own enumerable keys', version: 'v0.1' },
  { name: 'values', kind: 'method', receiver: 'object', signature: 'object.values(): any[]', description: 'Own enumerable values', version: 'v0.1' },
  { name: 'entries', kind: 'method', receiver: 'object', signature: 'object.entries(): [string, any][]', description: 'Own [key, value] pairs sorted by key', version: 'v0.1' },
  { name: 'has', kind: 'method', receiver: 'object', signature: 'object.has(key: string): boolean', description: 'True if object owns this key', version: 'v0.2' },
  { name: 'test', kind: 'method', receiver: 'regex', signature: 'regex.test(s: string): boolean', description: 'True if regex matches string', version: 'v0.4' },
]
