name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: xpr-lang/xpr-js
          path: ../xpr-js
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
