name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: xpr-playground
      - uses: actions/checkout@v4
        with:
          repository: xpr-lang/xpr-js
          path: xpr-js
      - uses: oven-sh/setup-bun@v2
      - run: bun install && bun run build
        working-directory: xpr-js
      - run: bun install
        working-directory: xpr-playground
      - run: bun run build
        working-directory: xpr-playground
      - run: bun run test:bundle
        working-directory: xpr-playground
      - run: bun run test:cross-runtime
        working-directory: xpr-playground
      - run: bun playwright install --with-deps
        working-directory: xpr-playground
      - run: bun playwright test
        working-directory: xpr-playground
